# import User from './user_def.graphql';
# import PageInfo from './common.graphql';
type Query {
  # 查询店铺
  shop(id: ID!): Shop
  shops(page_no: Int!, page_limit: Int): ShopPagination
}

type ShopPagination implements PageInfo {
  rows: [Shop]!
  total_items: Int!
  page_no: Int!
  page_limit: Int!
}

type Shop {
  _id: ID!
  name: String
  address: String
  isHead: Boolean
  avatar: String
  storePhone: String
  ownerId: ID!
  owner: User
}

input ShopInput {
  id: Int
  name: String
}

type Mutation {
  addShop(shopInput: ShopInput!): Shop
}
